const articles=[
{id:"skincare-pemula",cat:"Skincare",label:"Skincare",title:"Rutinitas Skincare Sederhana untuk Pemula",desc:"Mulai dari langkah paling dasar untuk merawat kulit secara sederhana dan konsisten.",content:"<p>Merawat kulit tidak harus rumit. Rutinitas sederhana yang dilakukan secara konsisten dapat menjadi langkah awal untuk menjaga kulit tetap bersih dan terawat.</p><h2>1. Bersihkan wajah</h2><p>Gunakan pembersih yang sesuai dengan kondisi kulit untuk membantu mengangkat kotoran, minyak, dan sisa produk.</p><h2>2. Gunakan pelembap</h2><p>Pelembap membantu menjaga kulit tetap terhidrasi dan mendukung skin barrier.</p><h2>3. Gunakan sunscreen</h2><p>Sunscreen membantu melindungi kulit dari paparan sinar matahari. Gunakan sesuai kebutuhan dan aktivitas sehari-hari.</p><h2>4. Jangan terlalu sering menyentuh wajah</h2><p>Tangan dapat membawa kotoran dan minyak yang dapat mengganggu kondisi kulit.</p><h2>5. Konsisten</h2><p>Rutinitas yang sederhana tetapi dilakukan secara konsisten biasanya lebih mudah dipertahankan daripada rutinitas yang terlalu rumit.</p><h2>Kesimpulan</h2><p>Mulailah perawatan kulit dari langkah sederhana dan pilih produk yang sesuai dengan kebutuhan kulitmu.</p>"},
{id:"makeup-natural",cat:"Makeup",label:"Makeup",title:"Tips Makeup Natural untuk Tampilan Fresh",desc:"Trik sederhana agar makeup terlihat ringan, natural, dan tetap fresh.",content:"<p>Makeup natural tidak berarti harus menggunakan banyak produk. Fokus pada tampilan yang ringan dan sesuai dengan kebutuhan wajah.</p><h2>1. Gunakan base tipis</h2><p>Pilih base yang ringan agar hasil makeup terlihat lebih natural.</p><h2>2. Rapikan alis</h2><p>Alis yang rapi dapat membantu membingkai wajah tanpa terlihat berlebihan.</p><h2>3. Tambahkan warna pada wajah</h2><p>Gunakan blush dan lip product dengan warna yang lembut untuk memberikan kesan fresh.</p><h2>Kesimpulan</h2><p>Kunci makeup natural adalah menggunakan produk secukupnya dan membaurkannya dengan baik.</p>"},
{id:"kesalahan-skincare",cat:"Beauty Tips",label:"Beauty Tips",title:"7 Kesalahan Skincare yang Sering Dilakukan",desc:"Kenali beberapa kebiasaan yang bisa membuat rutinitas skincare menjadi kurang efektif.",content:"<p>Rutinitas skincare bisa menjadi kurang efektif jika dilakukan dengan kebiasaan yang kurang tepat.</p><h2>1. Terlalu sering mencuci wajah</h2><p>Mencuci wajah secara berlebihan dapat membuat kulit terasa kering dan tidak nyaman.</p><h2>2. Tidak menggunakan sunscreen</h2><p>Perlindungan dari sinar matahari merupakan bagian penting dari perawatan kulit sehari-hari.</p><h2>3. Terlalu sering mengganti produk</h2><p>Memberikan waktu bagi kulit untuk beradaptasi dapat membantu kita mengetahui apakah suatu produk cocok.</p><h2>4. Mengabaikan pelembap</h2><p>Semua jenis kulit tetap membutuhkan hidrasi yang sesuai.</p><h2>5. Terlalu banyak produk</h2><p>Rutinitas yang terlalu banyak langkah tidak selalu lebih baik.</p><h2>6. Tidak membersihkan makeup</h2><p>Makeup sebaiknya dibersihkan dengan benar sebelum tidur.</p><h2>7. Tidak konsisten</h2><p>Perawatan kulit membutuhkan konsistensi agar rutinitas dapat berjalan dengan baik.</p><h2>Kesimpulan</h2><p>Perawatan kulit yang sederhana, sesuai kebutuhan, dan konsisten dapat menjadi pilihan yang lebih mudah dipertahankan.</p>"}
];

function qs(name){return new URLSearchParams(location.search).get(name)}
function renderCategory(){
 const cat=qs("cat")||"Beauty Tips"; document.getElementById("category-title").textContent=cat;
 const list=articles.filter(a=>a.cat===cat || cat==="Semua");
 const el=document.getElementById("category-list");
 el.innerHTML=(list.length?list:articles).map(a=>`<article class="category-card"><div class="thumb thumb-1">${a.label}</div><div><span class="tag">${a.cat}</span><h3><a href="article.html?id=${a.id}">${a.title}</a></h3><p>${a.desc}</p></div></article>`).join("");
}
function renderArticle(){
 const id=qs("id")||"skincare-pemula", a=articles.find(x=>x.id===id)||articles[0];
 document.title=a.title+" — BEAUTIVA";
 document.getElementById("article-content").innerHTML=document.getElementById("article-content").innerHTML=`<div class="article"><span class="tag">${a.cat}</span><h1>${a.title}</h1><p class="article-intro">${a.desc}</p><div class="article-body">${a.content}</div></div>`;
}
document.querySelector(".menu-btn")?.addEventListener("click",()=>document.querySelector("nav")?.classList.toggle("open"));
