const articles=[
{id:"skincare-pemula",cat:"Skincare",title:"Rutinitas Skincare Sederhana untuk Pemula",desc:"Mulai dari langkah paling dasar tanpa membuat rutinitas terasa ribet.",label:"SKINCARE",content:`<p>Rutinitas skincare tidak harus panjang untuk menjadi konsisten. Untuk pemula, fokuslah memahami kebutuhan kulit dan membangun kebiasaan yang sederhana.</p><h2>1. Kenali kebutuhan kulit</h2><p>Perhatikan bagaimana kulit terasa setelah mencuci wajah: apakah mudah terasa kering, berminyak, atau kombinasi. Ini menjadi titik awal untuk memilih produk yang sesuai.</p><h2>2. Mulai dari dasar</h2><p>Rutinitas dasar dapat berisi pembersih, pelembap, dan sunscreen pada pagi hari. Tambahkan produk lain secara bertahap jika memang dibutuhkan.</p><h2>3. Jangan terlalu cepat mengganti produk</h2><p>Memakai banyak produk sekaligus membuat kamu lebih sulit mengetahui produk mana yang cocok atau justru menyebabkan masalah. Konsistensi lebih penting daripada rutinitas yang panjang.</p><p><strong>Catatan:</strong> kondisi kulit setiap orang berbeda. Untuk keluhan kulit yang menetap atau berat, pertimbangkan berkonsultasi dengan dokter kulit.</p>`},
{id:"makeup-natural",cat:"Makeup",title:"Tips Makeup Natural untuk Tampilan Fresh",desc:"Trik sederhana agar makeup terlihat ringan, rapi, dan tetap natural.",label:"MAKEUP",content:`<p>Makeup natural bukan berarti tanpa produk. Kuncinya adalah menjaga hasil akhir tetap ringan dan memilih produk secukupnya.</p><h2>Mulai dengan base tipis</h2><p>Gunakan base secara tipis dan ratakan terutama di area yang membutuhkan coverage. Hindari menumpuk produk di seluruh wajah jika tidak diperlukan.</p><h2>Gunakan warna yang menyatu</h2><p>Pilih warna blush, lip product, dan alis yang terlihat harmonis dengan keseluruhan tampilan. Hasilnya akan terasa lebih effortless.</p><h2>Fokus pada satu area</h2><p>Jika ingin tampilan sehari-hari, pilih satu fitur untuk lebih ditonjolkan, misalnya mata atau bibir. Sisanya dibuat lebih soft.</p>`},
{id:"kesalahan-skincare",cat:"Beauty Tips",title:"7 Kesalahan Skincare yang Sering Dilakukan",desc:"Kenali kebiasaan yang bisa membuat rutinitas skincare kurang optimal.",label:"BEAUTY TIPS",content:`<p>Rutinitas skincare bisa terasa membingungkan ketika kita terlalu fokus pada banyak produk. Berikut beberapa kebiasaan yang sebaiknya diperhatikan.</p><h2>1. Terlalu banyak produk sekaligus</h2><p>Memulai banyak produk baru pada waktu yang sama membuat reaksi kulit sulit dilacak.</p><h2>2. Mengabaikan sunscreen</h2><p>Sunscreen merupakan bagian penting dari perlindungan kulit di siang hari. Gunakan sesuai petunjuk pada produk.</p><h2>3. Terlalu sering eksfoliasi</h2><p>Eksfoliasi berlebihan dapat membuat kulit terasa tidak nyaman. Ikuti petunjuk produk dan sesuaikan dengan toleransi kulit.</p><h2>4. Tidak membaca aturan pakai</h2><p>Setiap produk memiliki cara penggunaan berbeda. Baca label dan ikuti petunjuk penggunaan.</p><p>Ingat, skincare bukan kompetisi. Rutinitas yang sederhana dan konsisten sering kali lebih mudah dipertahankan.</p>`}
];

function qs(name){return new URLSearchParams(location.search).get(name)}
function renderCategory(){
 const cat=qs("cat")||"Beauty Tips"; document.getElementById("category-title").textContent=cat;
 const list=articles.filter(a=>a.cat===cat || cat==="Semua");
 const el=document.getElementById("category-list");
 el.innerHTML=(list.length?list:articles).map(a=>`<article class="category-card"><div class="thumb thumb-1">${a.label}</div><div><span class="tag">${a.cat}</span><h3><a href="article.html?id=${a.id}">${a.title}</a></h3><p>${a.desc}</p></div></article>`).join("");
}
function renderArticle(){
 const id=qs("id")||"skincare-pemula", a=articles.find(x=>x.id===id)||articles[0];
 document.title=a.title+" — BEAUTIVA";
 document.getElementById("article-content").innerHTML=`<div class="article"><span class="tag">${a.cat}</span><h1>${a.title}</h1><p class="article-meta">BEAUTIVA • Tips & Inspiration</p><div class="article-hero">${a.label}</div>${a.content}</div>`;
}
document.querySelector(".menu-btn")?.addEventListener("click",()=>document.querySelector("nav")?.classList.toggle("open"));